### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by devilbao** [wppconnect-team/wa-version#604]
![img_v3_02am_5a7f83a5-c7c8-465f-9c1d-d350e4982c5g](https://github.com/wppconnect-team/wa-version/assets/37796788/0b43731f-4224-40db-a2ad-48f218540669)

I tried all the methods in the issues but failed to solve my problem. please help me .

"whatsapp-web.js": "^1.23.0"
WhatsApp Web version: 2.3000.1011643235
Node.js version: v18.19.1

**Comment by kiriunin** [comment]
Same problem
