### ISSUE TITLE
Whatsapp version 2.2412.54 has been removed

### ISSUE THREAD

**Issue by ariagaluh02** [wppconnect-team/wa-version#608]
Recently I have been testing the application using WhatsApp web js.

But since version 2.2412.54 was removed, my app crashes after QR scan:

```
Initialize error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
 at __puppeteer_evaluation_script__:5:95
```

What has been done is to replace the version to the most recent version::
````
2.3000.1014550396-alpha.html
````

But it still doesn't work. Any update refer to whatsapp version?

**Comment by bumaruf** [comment]
same problem here, i tried using the removed version but it didn't work.

https://raw.githubusercontent.com/wppconnect-team/wa-version/c25a5543400ee5d94a5329a28a8d273100bf52ba/html/2.2412.54.html

**Comment by ashern000** [comment]
My application using WhatsApp web Js not works

**Comment by abdelrahman-tarek-0** [comment]
# there is some sort of expiration date to the 2.2412.54.html file

I am using WhatsApp web Js i uploaded the delete 2.2412.54.html in a personal repo and used it in my app
but I get an infinite update page

however, for anyone depending on 2.2412.54.html for a WhatsApp web JS bot 
there is a solution that worked for me 

delete the current whatsapp-web.js you have from package.json
and delete the node_module
then install this 
```
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
```

this version is from the WhatsApp web JS creator himself but on a different branch i don't know if it is stable or if there are features not included but for my use case it works fine 
and even without providing a webVersionCache for the bot client

```js
     this.client = new Client({
         puppeteer: {
            headless: true,
         },
         authStrategy: new LocalAuth({
            clientId: this.id,
            dataPath: this.sessionPath,
         }),
      })
```

working on my bot server
![image](https://github.com/wppconnect-team/wa-version/assets/92829578/39078533-c2b1-4882-baf0-f0ebaefa69f5)

**Comment by ingGhost** [comment]
same error here, anyone got solution?

**Comment by vismaygamit** [comment]
> Recently I have been testing the application using WhatsApp web js.
> 
> But since version 2.2412.54 was removed, my app crashes after QR scan:
> 
> ```
> Initialize error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
>  at __puppeteer_evaluation_script__:5:95
> ```
> 
> What has been done is to replace the version to the most recent version::
> 
> ```
> 2.3000.1014550396-alpha.html
> ```
> 
> But it still doesn't work. Any update refer to whatsapp version?

try this one 2.2413.51-beta.html , it work for me

**Comment by estnov** [comment]
> > Recently I have been testing the application using WhatsApp web js.
> > But since version 2.2412.54 was removed, my app crashes after QR scan:
> > ```
> > Initialize error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
> >  at __puppeteer_evaluation_script__:5:95
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What has been done is to replace the version to the most recent version::
> > ```
> > 2.3000.1014550396-alpha.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it still doesn't work. Any update refer to whatsapp version?
> 
> try this one webVersion: '2.2413.51-beta', webVersionCache: { type: 'remote', remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2413.51-beta.html', }, it work for me

Same here, currently I set my Client like this: 

`this.client = new Client({ 
            authStrategy: new LocalAuth({
                dataPath: 'session'
            }),
            webVersionCache: {
                remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2413.51-beta.html',
                type: 'remote'
            },
            puppeteer: { 
                headless: true, 
                args: [ 
                    '--no-sandbox', 
                    '--disable-setuid-sandbox', 
                    '--disable-dev-shm-usage', 
                    '--single-process', 
                    '--no-zygote', 
                    '--no-first-run', 
                    '--no-default-browser-check', 
                    '--disable-extensions', 
                    '--disable-default-apps', 
                    '--disable-sync', 
                    '--disable-translate', 
                    '--disable-web-security', 
                    '--disable-features=site-per-process', 
                    '--disable-infobars', 
                    '--window-position=0,0', 
                    '--ignore-certificate-errors', 
                    '--ignore-certificate-errors-spki-list', 
                    '--disable-gpu', 
                    '--disable-webgl', 
                    '--disable-threaded-animation', 
                    '--disable-threaded-scrolling', 
                    '--disable-in-process-stack-traces', 
                    '--disable-histogram-customizer', 
                    '--disable-gl-extensions', 
                    '--disable-composited-antialiasing', 
                    '--disable-canvas-aa', 
                    '--disable-3d-apis', 
                    '--disable-accelerated-2d-canvas', 
                    '--disable-accelerated-jpeg-decoding', 
                    '--disable-accelerated-mjpeg-decode', 
                    '--disable-app-list-dismiss-on-blur', 
                    '--disable-accelerated-video-decode' 
                ] } 
            }
        );`

I also updated the libraries to the latest version by:
`npm cache clean --force  `

And then:
`npm install puppeteer@22.12.1 --save-exact  `
`npm install whatsapp-web.js@1.24.0 --save-exact`

Now it's working, but I am concerned about the maintenance of my chatbot as the version.json of this project indicates that version 2.2413.51-beta expires on "2024-06-30T23:19:19.506Z".

**Comment by ariagaluh02** [comment]
> # there is some sort of expiration date to the 2.2412.54.html file
> I am using WhatsApp web Js i uploaded the delete 2.2412.54.html in a personal repo and used it in my app but I get an infinite update page
> 
> however, for anyone depending on 2.2412.54.html for a WhatsApp web JS bot there is a solution that worked for me
> 
> delete the current whatsapp-web.js you have from package.json and delete the node_module then install this
> 
> ```
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> ```
> 
> this version is from the WhatsApp web JS creator himself but on a different branch i don't know if it is stable or if there are features not included but for my use case it works fine and even without providing a webVersionCache for the bot client
> 
> ```js
>      this.client = new Client({
>          puppeteer: {
>             headless: true,
>          },
>          authStrategy: new LocalAuth({
>             clientId: this.id,
>             dataPath: this.sessionPath,
>          }),
>       })
> ```
> 
> working on my bot server ![image](https://private-user-images.githubusercontent.com/92829578/344215307-39078533-c2b1-4882-baf0-f0ebaefa69f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzI2NDYsIm5iZiI6MTcxOTYzMjM0NiwicGF0aCI6Ii85MjgyOTU3OC8zNDQyMTUzMDctMzkwNzg1MzMtYzJiMS00ODgyLWJhZjAtZjBlYmFlZmE2OWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDAzMzkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWRlOTM2YzViODNjNGZjMWFlNWQ4YzI5Mjg1Y2YwZjczYjE3MDQyOTVjMDI3YjkyNTAxMjc1MjUxYTE5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e4SBrHxxlNSrBKiQvRWyy7zjI8nty57xEowg9951imY)

It's working!
Like you said, what I do is change the whatsapp web js version in package.json from  ```whatsapp-web.js": "1.23.1-alpha.5 ```  to ```github:pedroslopez/whatsapp-web.js#webpack-exodus```

Then I rebuild my Docker. Now after I scan my QR, the apps running well. Thank you!

**Comment by sagirr** [comment]
Hi

29 Haz 2024 Cmt 07:08 tarihinde Aria Galuh ***@***.***> şunu
yazdı:

**Comment by sagirr** [comment]
29 Haz 2024 Cmt 13:16 tarihinde Şagiir ***@***.***> şunu yazdı:

**Comment by sagirr** [comment]
Steps to Reproduce the Bug or Issue

   1. Install latest everything
   2. use this webchache version : webVersionCache:
   {
   type: 'remote' ,
   remotePath: '
   https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014251604-alpha.html
   '
   }

3.here is the new alpha files
4.and run the code and scan the qr.

29 Haz 2024 Cmt 13:19 tarihinde Şagiir ***@***.***> şunu yazdı:

**Comment by kanglerian** [comment]
> # ada semacam tanggal kedaluwarsa pada file 2.2412.54.html
> Saya menggunakan WhatsApp web Js saya mengunggah delete 2.2412.54.html dalam repo pribadi dan menggunakannya di aplikasi saya tapi saya mendapatkan halaman pembaruan tanpa batas
> 
> namun, bagi siapa pun tergantung pada 2.2412.54.html untuk bot web WhatsApp JS ada solusi yang berhasil untuk saya
> 
> hapus whatsapp-web.js saat ini yang Anda miliki dari package.json dan hapus node_module lalu instal ini
> 
> ```
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> ```
> 
> versi ini berasal dari pembuat web WhatsApp JS sendiri tetapi pada cabang yang berbeda saya tidak tahu apakah itu stabil atau jika ada fitur yang tidak termasuk tetapi untuk kasus penggunaan saya itu bekerja dengan baik dan bahkan tanpa menyediakan webVersionCache untuk klien bot
> 
> ```js
>      this.client = new Client({
>          puppeteer: {
>             headless: true,
>          },
>          authStrategy: new LocalAuth({
>             clientId: this.id,
>             dataPath: this.sessionPath,
>          }),
>       })
> ```
> 
> bekerja di server bot saya ![gambar](https://private-user-images.githubusercontent.com/92829578/344215307-39078533-c2b1-4882-baf0-f0ebaefa69f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTAwNDUsIm5iZiI6MTcxOTgwOTc0NSwicGF0aCI6Ii85MjgyOTU3OC8zNDQyMTUzMDctMzkwNzg1MzMtYzJiMS00ODgyLWJhZjAtZjBlYmFlZmE2OWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA0NTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTYwYWJmY2YwMWViOTZmM2MzMzQ2ZWM2YmRkMzNmYzI2MTYxOTBkMGVlYjJmZmI1Njc0NzY1NWY5MWIyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FhTb9mhZIC38sSD_6RhTn_I5dbeEPSxRsFJgYH0caeo)

Makasih pak eko! ieu bener bener work euy jagoan si bapak eta
