### ISSUE TITLE
File missing in wa-version/html

### ISSUE THREAD

**Issue by RahGeer** [wppconnect-team/wa-version#610]
Latest version has been specified in versions.json file but it's missing in the html folder ... And so we're still getting the Evaluation failed error.

**Comment by adnansiddiq** [comment]
facing same issue.

**Comment by ReddyGopichand** [comment]
getting same error,please add latest version html file

**Comment by foodcodechat** [comment]
Same here the version 2.2413.5 tpe remote is not working :/

**Comment by rizkihermansyah83** [comment]
same problems.. helpme please sir... thanks

**Comment by yairmelamed** [comment]
me too.. please help..

**Comment by RahGeer** [comment]
Apparently the way out right now is to install Pedro's exodus version and not use webversioncache

**Comment by RahGeer** [comment]
Fix identified in other threads
