### ISSUE TITLE
When Will a Usable Version Be Released? We Are Experiencing Issues

### ISSUE THREAD

**Issue by erenn44** [wppconnect-team/wa-version#619]
We are experiencing issues; when will a usable version be released?

**Comment by icleitoncosta** [comment]
> We are experiencing issues; when will a usable version be released?

What problem are you facing?

**Comment by erenn44** [comment]
My problem is that it says it is synchronizing and it never finishes and does not send a message. I think it is related to the version.

**Comment by icleitoncosta** [comment]
Hi, check your code and project, all versions is usable and are in use in wppconnnect
